-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds:
-- - https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- - $LAZYVIM_DIR/lua/lazyvim/config/autocmds.lua
