-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps:
-- - https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- - $LAZYVIM_DIR/lua/lazyvim/config/keymaps.lua
